### ISSUE TITLE
Is it possible to have labels always show above bars in a Bar Chart?

### ISSUE THREAD

**Issue by donpinkus** [esripdx/angular-dimple#51]
I have a bar chart, and I'd like to show the Y-value labels above each bar.

Is this possible in dimple.js / angular-dimple? I'm not seeing any mention of it in the docs.

**Comment by paulcpederson** [comment]
Not sure if that is possible in dimple.js, if it is it would be a pretty simple addition to angular-dimple. But I'm not sure.

**Comment by paulcpederson** [comment]
Maybe @johnkiernander would know?

**Comment by johnkiernander** [comment]
There's nothing in the API for labelling but it's something I do a lot in our own implementations with a bit of post processing in d3.  The only reason it isn't in the API is just because it needs to be dealt with as part of a larger universal piece adding labels everywhere - which is big and complicated.  Writing it for any single implementation is fairly straightforward though: http://jsbin.com/suyiwa/3/edit

**Comment by paulcpederson** [comment]
@donpinkus I am going to close this as I think john answered the question. 

Looks like this is something tgat is possible, but not going to be part of dimple or angular dimple anytime soon.
